import { test, expect } from "@playwright/test";
import { setupPage, SettingsHelpers } from "../test-utils";

/**
 * Test language switching in the calculator.
 * These tests verify that the i18n system works correctly.
 */

/* This is slop generated by Claude because I was wayy too lazy to write this many tests myself. :) */

test.describe("Language Settings", () => {
	test.describe("Language Selection", () => {
		test("English is set by test setup", async ({ page }) => {
			await setupPage(page);
			const settings = new SettingsHelpers(page);

			await settings.open();
			// Verify English is shown in dropdown
			await expect(page.getByText("English")).toBeVisible();
		});

		test("can switch to Finnish", async ({ page }) => {
			await setupPage(page);
			const settings = new SettingsHelpers(page);

			await settings.open();

			// Open language dropdown
			await page.locator("button", { hasText: "English" }).click();
			// Wait for options to be visible (menu may be animated)
			await expect(page.getByRole("button", { name: "Finnish", exact: true })).toBeVisible();

			// Select Finnish (displayed as "Finnish" in English UI)
			await page.getByRole("button", { name: "Finnish", exact: true }).click();

			// Verify Finnish is now selected
			await expect(page.getByText("Suomi")).toBeVisible();

			// Verify UI elements are translated
			await expect(page.getByText("Kulman yksikkö")).toBeVisible();
		});

		test("can switch to Swedish", async ({ page }) => {
			await setupPage(page);
			const settings = new SettingsHelpers(page);

			await settings.open();

			// Open language dropdown
			await page.locator("button", { hasText: "English" }).click();
			// Wait for options to be visible
			await expect(page.getByRole("button", { name: "Swedish", exact: true })).toBeVisible();

			// Select Swedish (displayed as "Swedish" in English UI)
			await page.getByRole("button", { name: "Swedish", exact: true }).click();

			// Verify Swedish is now selected
			await expect(page.getByText("Svenska")).toBeVisible();
		});

		test("language persists in localStorage", async ({ page }) => {
			await setupPage(page);
			const settings = new SettingsHelpers(page);

			await settings.open();

			// Open language dropdown and switch to Finnish (displayed as "Finnish")
			await page.locator("button", { hasText: "English" }).click();
			await expect(page.getByRole("button", { name: "Finnish", exact: true })).toBeVisible();
			await page.getByRole("button", { name: "Finnish", exact: true }).click();

			const storedValue = await page.evaluate(() => localStorage.getItem("abicus-language"));
			expect(storedValue).toBe("fi");
		});
	});

	test.describe("Translated UI Elements", () => {
		test("settings labels are translated to Finnish", async ({ page }) => {
			// Set Finnish before loading
			await page.addInitScript(() => {
				localStorage.setItem("abicus-language", "fi");
			});
			await page.goto("/");

			const settings = new SettingsHelpers(page);
			await settings.open();

			// Verify Finnish translations appear
			await expect(page.getByText("Kulman yksikkö")).toBeVisible();
			await expect(page.getByText("Asteet")).toBeVisible();
			await expect(page.getByText("Radiaanit")).toBeVisible();
		});

		test("settings labels are translated to Swedish", async ({ page }) => {
			// Set Swedish before loading
			await page.addInitScript(() => {
				localStorage.setItem("abicus-language", "sv");
			});
			await page.goto("/");

			const settings = new SettingsHelpers(page);
			await settings.open();

			// Verify Swedish translations appear
			await expect(page.getByText("Vinkelenhet")).toBeVisible();
			await expect(page.getByText("Grader")).toBeVisible();
			await expect(page.getByText("Radianer")).toBeVisible();
		});
	});

	test.describe("Calculator Works in All Languages", () => {
		test("calculations work with Finnish language", async ({ page }) => {
			await page.addInitScript(() => {
				localStorage.setItem("abicus-language", "fi");
			});
			await page.goto("/");

			// Basic calculation should still work
			await page.getByRole("textbox").fill("5+5");
			await page.getByRole("button", { name: "=", exact: true }).click();

			await expect(page.getByRole("status")).toHaveText("10");
		});

		test("calculations work with Swedish language", async ({ page }) => {
			await page.addInitScript(() => {
				localStorage.setItem("abicus-language", "sv");
			});
			await page.goto("/");

			// Basic calculation should still work
			await page.getByRole("textbox").fill("7*8");
			await page.getByRole("button", { name: "=", exact: true }).click();

			await expect(page.getByRole("status")).toHaveText("56");
		});
	});
});
