import { test, expect } from "@playwright/test";
import { setupPage, CalculatorHelpers, SettingsHelpers } from "../test-utils";
/* This, too is slop generated by Claude because I was too lazy to write this many tests myself. :) */

test.beforeEach(async ({ page }) => {
	await setupPage(page);
});

test.describe.skip("Advanced Settings (Deprecated)", () => {
	test.describe("Decimal Separator Settings", () => {
		test("can switch decimal separator to period", async ({ page }) => {
			const settings = new SettingsHelpers(page);
			const calc = new CalculatorHelpers(page);

			await settings.open();
			// Find and click the period separator option
			await page.getByRole("button", { name: ".", exact: true }).click();
			await settings.close();

			// Test calculation with decimal
			await calc.calculate("3.14 * 2", "button");
			// Result should use period as decimal separator
			const result = await calc.getResult().textContent();
			expect(result).toContain(".");
			expect(result).not.toContain(",");
		});

		test("decimal separator persists in localStorage", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();
			await page.getByRole("button", { name: ".", exact: true }).click();
			await settings.close();

			const storedValue = await page.evaluate(() => localStorage.getItem("abicus-decimal-separator"));
			expect(storedValue).toBe(".");
		});

		test("decimal separator persists across page reloads", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			// Switch to period separator
			await settings.open();
			await page.getByRole("button", { name: ".", exact: true }).click();
			await settings.close();

			// Reload page
			await page.reload();

			// Verify setting persisted
			await settings.open();
			await expect(page.getByRole("button", { name: ".", exact: true })).toBeDisabled();
		});
	});

	test.describe("Theme Settings", () => {
		test("can switch to dark mode", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();
			await page.getByRole("button", { name: "Dark", exact: true }).click();
			await settings.close();

			// Verify dark mode is applied (check for dark class on html element)
			const htmlClass = await page.evaluate(() => document.documentElement.classList.contains("dark"));
			expect(htmlClass).toBe(true);
		});

		test("can switch back to light mode", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			// First switch to dark mode
			await settings.open();
			await page.getByRole("button", { name: "Dark", exact: true }).click();
			await settings.close();

			// Then switch back to light mode
			await settings.open();
			await page.getByRole("button", { name: "Light", exact: true }).click();
			await settings.close();

			// Verify dark mode is removed
			const htmlClass = await page.evaluate(() => document.documentElement.classList.contains("dark"));
			expect(htmlClass).toBe(false);
		});

		test("dark mode persists in localStorage", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();
			await page.getByRole("button", { name: "Dark", exact: true }).click();
			await settings.close();

			const storedValue = await page.evaluate(() => localStorage.getItem("abicus-dark-mode"));
			expect(storedValue).toBe("true");
		});

		test("dark mode persists across page reloads", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();
			await page.getByRole("button", { name: "Dark", exact: true }).click();
			await settings.close();

			await page.reload();

			const htmlClass = await page.evaluate(() => document.documentElement.classList.contains("dark"));
			expect(htmlClass).toBe(true);
		});
	});

	test.describe("Font Size Settings", () => {
		test("can increase font size", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();

			// Get initial font size
			const initialFontSize = await page.evaluate(() => localStorage.getItem("abicus-font-size") || "16");

			// Find and click the increase button (+ button for font size)
			const increaseButton = page.locator("button", { hasText: "+" }).first();
			await increaseButton.click();

			await settings.close();

			const newFontSize = await page.evaluate(() => localStorage.getItem("abicus-font-size"));
			expect(parseInt(newFontSize || "16")).toBeGreaterThan(parseInt(initialFontSize));
		});

		test("can decrease font size", async ({ page }) => {
			const settings = new SettingsHelpers(page);

			await settings.open();

			// First increase to make sure we can decrease
			const increaseButton = page.locator("button", { hasText: "+" }).first();
			await increaseButton.click();
			await increaseButton.click();

			const increasedFontSize = await page.evaluate(() => localStorage.getItem("abicus-font-size") || "16");

			// Now decrease
			const decreaseButton = page.locator("button", { hasText: "−" }).first();
			await decreaseButton.click();

			await settings.close();

			const newFontSize = await page.evaluate(() => localStorage.getItem("abicus-font-size"));
			expect(parseInt(newFontSize || "16")).toBeLessThan(parseInt(increasedFontSize));
		});
	});

	test.describe("Clear Functions", () => {
		test("Clear All button clears expression and memory", async ({ page }) => {
			const calc = new CalculatorHelpers(page);
			const settings = new SettingsHelpers(page);

			// Store something in memory first
			await page.getByRole("textbox").fill("42");
			await page.getByRole("button", { name: "Min", exact: true }).click();

			// Now clear all
			await settings.open();
			await page.getByRole("button", { name: "Clear All", exact: true }).click();
			await settings.close();

			// Memory should be cleared
			await page.getByRole("button", { name: "Mout", exact: true }).click();
			await page.getByRole("button", { name: "=", exact: true }).click();
			// M should evaluate to 0 after clear
			await expect(calc.getResult()).toHaveText("0");
		});
	});
});
